# Generated by Django 5.1.5 on 2025-01-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diary",
            name="label",
            field=models.IntegerField(
                blank=True, choices=[(0, "Negative"), (1, "Positive")], null=True
            ),
        ),
    ]
