# Generated by Django 5.1.5 on 2025-02-04 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyApp", "0003_alter_catprofile_catprofile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advice",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
