# Generated by Django 5.1.5 on 2025-02-04 16:33

import arrow.api
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyApp", "0004_alter_advice_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="ชื่อวิดีโอ")),
                (
                    "video_file",
                    models.FileField(upload_to="videos/", verbose_name="ไฟล์วิดีโอ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=arrow.api.now, verbose_name="วันที่สร้าง"
                    ),
                ),
            ],
        ),
    ]
