# Generated by Django 5.1.5 on 2025-02-06 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyApp", "0005_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catprofile",
            name="cat_age",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="catprofile",
            name="cat_birthday",
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="catprofile",
            name="cat_breed",
            field=models.CharField(default="Unknown", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="catprofile",
            name="cat_fav",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="catprofile",
            name="cat_gender",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="catprofile",
            name="cat_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="catprofile",
            name="catprofile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="catprofile_image/"
            ),
        ),
        migrations.AddConstraint(
            model_name="catprofile",
            constraint=models.UniqueConstraint(
                fields=("owner", "cat_name"), name="unique_owner_cat"
            ),
        ),
        migrations.AlterModelTable(
            name="catprofile",
            table=None,
        ),
    ]
