# Generated by Django 5.1.5 on 2025-02-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyApp", "0006_alter_catprofile_cat_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video_file", models.FileField(upload_to="diary_videos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="memoryvideo",
            name="user",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
        migrations.DeleteModel(
            name="MemoryVideo",
        ),
    ]
